import React from 'react'
import Heading from './components/Heading';

const privacy = () => {
  return (

 

    <>
    <Heading title={'Privacy Policy'} subtitle={'We care about your privacy'} imageSrc={'/images/cards/holiday5.jpg'}  />
    <div className="container mx-auto px-10">
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <strong>
            <span style={{ fontFamily: "SimSun" }}>
              <strong>Updated at 2022-07-14</strong>
            </span>
          </strong>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            {`Excel Travel Services. ("we," "our," or "us") is committed to
            protecting your privacy. This Privacy Policy explains how your
            personal`}
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            information is collected, used, and disclosed by Excel Travel
            Services.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            This Privacy Policy applies to our website,
            https://www.exceltravelservices.com , and its associated subdomains
            (collectively, our
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            "Service"). By accessing or using our Service, you signify that you
            have read, understood, and agree to our collection, storage, use,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            and disclosure of your personal information as described in this
            Privacy Policy and our Terms of Service.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <strong>
            <span style={{ fontFamily: "SimSun" }}>
              <strong>For this Privacy Policy:</strong>
            </span>
          </strong>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            * Cookie: small amount of data generated by a website and saved by
            your web browser. It is used to identify your browser,
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            provide analytics, remember information about you such as your
            language preference or login information.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Company: when this policy mentions&nbsp;
            </span>
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              “
            </span>
            <span style={{ fontFamily: "SimSun" }}>Company,</span>
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              ” “
            </span>
            <span style={{ fontFamily: "SimSun" }}>we,</span>
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              ” “
            </span>
            <span style={{ fontFamily: "SimSun" }}>us,</span>
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              ”&nbsp;
            </span>
            <span style={{ fontFamily: "SimSun" }}>or&nbsp;</span>
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              “
            </span>
            <span style={{ fontFamily: "SimSun" }}>our,</span>
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              ”&nbsp;
            </span>
            <span style={{ fontFamily: "SimSun" }}>
              it refers to Excel Travel Services, PO Box 814, Hicksville,
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            NY 11802 that is responsible for your information under this Privacy
            Policy.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            + Country: where Excel Travel Services or the owners/founders of
            Excel Travel Services are based, in this case is USA.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Customer: refers to the company, organization or person that signs
              up to use the Excel Travel Services Service to manage the
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            relationships with your consumers or service users.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            * Device: any internet connected device such as a phone, tablet,
            computer or any other device that can be used to visit Excel
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            Travel Services and use the services.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              IP address: Every device connected to the Internet is assigned a
              number known as an Internet protocol (IP) address. These
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            numbers are usually assigned in geographic blocks. An IP address can
            often be used to identify the location from which a
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            device is connecting to the Internet.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Personnel: refers to those individuals who are employed by Excel
              Travel Services or are under contract to perform a service on
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            behalf of one of the parties.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Personal Data: any information that directly, indirectly, or in
              connection with other information&nbsp;
            </span>
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              —&nbsp;
            </span>
            <span style={{ fontFamily: "SimSun" }}>including a personal</span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            identification number&nbsp;
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              —&nbsp;
            </span>
            <span style={{ fontFamily: "SimSun" }}>
              allows for the identification or identifiability of a natural
              person.
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            * Service: refers to the service provided by Excel Travel Services
            as described in the relative terms (if available) and on this
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>platform.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Third-party service: refers to advertisers, contest sponsors,
              promotional and marketing partners, and others who provide our
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            content or whose products or services we think may interest you.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            + Website: Excel Travel Services's site, which can be accessed via
            this URL:
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            https://www.exceltravelservices.com.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              You: a person or entity that is registered with Excel Travel
              Services to use the Services.
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We collect information from you when you visit our service,
            register, place an order, subscribe to our newsletter, respond to a
            survey
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>or fill out a form.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>+ Name / Username</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>+ Phone Numbers</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>+ Email Addresses</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>* Mailing Addresses</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>+ Job Titles</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>Billing Addresses</span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            + Debit/credit card numbers
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            »&nbsp;<span style={{ fontFamily: "SimSun" }}>Age</span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>+ Password</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We also collect information from mobile devices for a better user
            experience, although these features are completely optional:
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Any of the information we collect from you may be used in one of the
            following ways:
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              To personalize your experience (your information helps us to
              better respond to your individual needs)
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              To improve our service (we continually strive to improve our
              service offerings based on the information and feedback we receive
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>from you)</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              To improve customer service (your information helps us to more
              effectively respond to your customer service requests and
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>support needs)</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            * To process transactions
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            * To administer a contest, promotion, survey or other site feature
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              To send periodic emails
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We receive some information from the third parties when you contact
            us. For example, when you submit your email address to us to
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            show interest in becoming our customer, we receive information from
            a third party that provides automated fraud detection services to
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            us. We also occasionally collect information that is made publicly
            available on social media websites. You can control how much of
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            your information social media websites make public by visiting these
            websites and changing your privacy settings.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We may share the information that we collect, both personal and
            non-personal, with third parties such as advertisers, contest
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            sponsors, promotional and marketing partners, and others who provide
            our content or whose products or services we think may
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            interest you. We may also share it with our current and future
            affiliated companies and business partners, and if we are involved
            ina
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            merger, asset sale or other business reorganization, we may also
            share or transfer your personal and non-personal information to our
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>successors-in-interest.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We may engage trusted third party service providers to perform
            functions and provide services to us, such as hosting and
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            maintaining our servers and our service, database storage and
            management, e-mail management, storage marketing, credit card
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            processing, customer service and fulfilling orders for products and
            services you may purchase through our platform. We will likely
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            share your personal information, and possibly some non-personal
            information, with these third parties to enable them to perform
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            these services for us and for you.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We may share portions of our log file data, including IP addresses,
            for analytics purposes with third parties such as web analytics
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            partners, application developers, and ad networks. If your IP
            address is shared, it may be used to estimate general location and
            other
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            technographics such as connection speed, whether you have visited
            the service in a shared location, and type of device used to visit
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            the service. They may aggregate information about our advertising
            and what you see on the service and then provide auditing,
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            research and reporting for us and our advertisers.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We may also disclose personal and non-personal information about you
            to government or law enforcement officials or private parties
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            as we, in our sole discretion, believe necessary or appropriate in
            order to respond to claims, legal process (including subpoenas), to
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            protect our rights and interests or those of a third party, the
            safety of the public or any person, to prevent or stop any illegal,
            unethical,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            or legally actionable activity, or to otherwise comply with
            applicable court orders, laws, rules and regulations.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We will collect personal information that you submit to us. We may
            also receive personal information about you from third parties as
          </span>
          &nbsp;<span style={{ fontFamily: "SimSun" }}>described above.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            By submitting your email address on this website, you agree to
            receive emails from us. You can cancel your participation in any of
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            these email lists at any time by clicking on the opt-out link or
            other unsubscribe option that is included in the respective email.
            We
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            only send emails to people who have authorized us to contact them,
            either directly, or through a third party. We do not send
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            unsolicited commercial emails, because we hate spam as much as you
            do. By submitting your email address, you also agree to allow
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            us to use your email address for customer audience targeting on
            sites like Facebook, where we display custom advertising to specific
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            people who have opted-in to receive communications from us. Email
            addresses submitted only through the order processing page
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            will be used for the sole purpose of sending you information and
            updates pertaining to your order. If, however, you have provided the
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            same email to us through another method, we may use it for any of
            the purposes stated in this Policy. Note: If at any time you would
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            like to unsubscribe from receiving future emails, we include
            detailed unsubscribe instructions at the bottom of each email.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We are incorporated in USA. Information collected via our website,
            through direct interactions with you, or from use of our help
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            services may be transferred from time to time to our offices or
            personnel, or to third parties, located throughout the world, and
            may be
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            viewed and hosted anywhere in the world, including countries that
            may not have laws of general applicability regulating the use and
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            transfer of such data. To the fullest extent allowed by applicable
            law, by using any of the above, you voluntarily consent to the
            trans-border transfer and hosting of such information.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We take precautions to protect the security of your information. We
            have physical, electronic, and managerial procedures to help
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            safeguard, prevent unauthorized access, maintain data security, and
            correctly use your information. However, neither people nor
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            security systems are foolproof, including encryption systems. In
            addition, people can commit intentional crimes, make mistakes or
            fail
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            to follow policies. Therefore, while we use reasonable efforts to
            protect your personal information, we cannot guarantee its absolute
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            security. If applicable law imposes any&nbsp;
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            on-disclaimable duty to protect your personal information, you agree
            that intentional
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            misconduct will be the standards used to measure our compliance with
            that duty.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            The rights you have to request updates or corrections to the
            information we collect depend on your relationship with us.
            Personnel
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            may update or correct their information as detailed in our internal
            company employment policies. Customers have the right to request
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            the restriction of certain uses and disclosures of personally
            identifiable information as follows. You can contact us in order to
            (1)
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            update or correct your personally identifiable information, (2)
            change your preferences with respect to communications and other
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            information you receive from us, or (3) delete the personally
            identifiable information maintained about you on our systems
            (subject to
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            the following paragraph), by cancelling your account. Such updates,
            corrections, changes and deletions will have no effect on other
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            information that we maintain, or information that we have provided
            to third parties in accordance with this Privacy Policy prior to
            such
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            update, correction, change or deletion. To protect your privacy and
            security, we may take reasonable steps (such as requesting a
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            unique password) to verify your identity before granting you profile
            access or making corrections. You are responsible for maintaining
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            the secrecy of your unique password and account information at all
            times. You should be aware that it is not technologically possible
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            to remove each and every record of the information you have provided
            to us from our system. The need to back up our systems to
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            protect information from inadvertent loss means that a copy of your
            information may exist in a non-erasable form that will be difficult
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            or impossible for us to locate. Promptly after receiving your
            request, all personal information stored in databases we actively
            use, and
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            other readily searchable media will be updated, corrected, changed
            or deleted, as appropriate, as soon as and to the extent
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            reasonably and technically practicable. If you are an end user and
            wish to update, delete, or receive any information we have about
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            you, you may do so by contacting the organization of which you are a
            customer.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            If you are one of our workers or applicants, we collect information
            you voluntarily provide to us. We use the information collected for
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            Human Resources purposes in order to administer benefits to workers
            and screen applicants. You may contact us in order to (1)
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            update or correct your information, (2) change your preferences with
            respect to communications and other information you receive
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            from us, or (3) receive a record of the information we have relating
            to you. Such updates, corrections, changes and deletions will
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            have no effect on other information that we maintain, or information
            that we have provided to third parties in accordance with this
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Privacy Policy prior to such update, correction, change or deletion.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We reserve the right to transfer information to a third party in the
            event of a sale, merger or other transfer of all or substantially
            all of
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            the assets of us or any of its Corporate Affiliates (as defined
            herein), or that portion of us or any of its Corporate Affiliates to
            which the
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            Service relates, or in the event that we discontinue our business or
            file a petition or have filed against us a petition in bankruptcy,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            reorganization or similar proceeding, provided that the third party
            agrees to adhere to the terms of this Privacy Policy.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We may disclose information (including personal information) about
            you to our Corporate Affiliates. For purposes of this Privacy
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            Policy, "Corporate Affiliate" means any person or entity which
            directly or indirectly controls, is controlled by or is under
            common.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            control with us, whether by ownership or otherwise. Any information
            relating to you that we provide to our Corporate Affiliates will be
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            treated by those Corporate Affiliates in accordance with the terms
            of this Privacy Policy.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We keep your information only so long as we need it to provide
            service to you and fulfill the purposes described in this policy.
            This is
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            also the case for anyone that we share your information with and who
            carries out services on our behalf. When we no longer need to
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            use your information and there is no need for us to keep it to
            comply with our legal or regulatory obligations, we'll either remove
            it
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            from our systems or depersonalize it so that we can't identify you.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We implement a variety of security measures to maintain the safety
            of your personal information when you place an order or enter,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            submit, or access your personal information. We offer the use of a
            secure server. All supplied sensitive/credit information is
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            transmitted via Secure Socket Layer (SSL) technology and then
            encrypted into our Payment gateway providers database only to be
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            accessible by those authorized with special access rights to such
            systems, and are required to keep the information confidential.
            After
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            a transaction, your private information (credit cards, social
            security numbers, financials, etc.) is never kept on file. We
            cannot,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            however, ensure or warrant the absolute security of any information
            you transmit to us or guarantee that your information on the
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            Service may not be accessed, disclosed, altered, or destroyed by a
            breach of any of our physical, technical, or managerial
          </span>
          &nbsp;<span style={{ fontFamily: "SimSun" }}>safeguards.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            The laws of USA, excluding its conflicts of law rules, shall govern
            this Agreement and your use of our service. Your use of our service
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            may also be subject to other local, state, national, or
            international laws.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            By using our service, registering an account, or making a purchase,
            you consent to this Privacy Policy.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            This Privacy Policy applies only to the Services. The Services may
            contain links to other websites not operated or controlled by . We
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            are not responsible for the content, accuracy or opinions expressed
            in such websites, and such websites are not investigated,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            monitored or checked for accuracy or completeness by us. Please
            remember that when you use a link to go from the Services to
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            another website, our Privacy Policy is no longer in effect. Your
            browsing and interaction on any other website, including those that
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            have a link on our platform, is subject to that website's own rules
            and policies. Such third parties may use their own cookies or other
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            methods to collect information about you.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We use "Cookies" to identify the areas of our website that you have
            visited. A Cookie is a small piece of data stored on your computer
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            or mobile device by your web browser. We use Cookies to personalize
            the Content that you see on our website. Most web browsers
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            can be set to disable the use of Cookies. However, if you disable
            Cookies, you may not be able to access functionality on our website
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            correctly or at all. We never place Personally Identifiable
            Information in Cookies.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Advertising keeps us and many of the websites and services you use
            free of charge. We work hard to make sure that ads are safe,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            unobtrusive, and as relevant as possible.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Cookies help to make advertising more effective. Without cookies,
            it's really hard for an advertiser to reach its audience, or to know
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            how many ads were shown and how many clicks they received.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We use remarketing services. What Is Remarketing? In digital
            marketing, remarketing (or retargeting) is the practice of serving
            ads
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            across the internet to people who have already visited your website.
            It allows your company to seem like they're&nbsp;
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              “
            </span>
            <span style={{ fontFamily: "SimSun" }}>following</span>
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              ”&nbsp;
            </span>
            <span style={{ fontFamily: "SimSun" }}>people</span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            around the internet by serving ads on the websites and platforms
            they use most.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            In respect to any credit card or other payment processing details
            you have provided us, we commit that this confidential information
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            will be stored in the most secure manner possible.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <strong>
            <span style={{ fontFamily: "SimSun" }}>
              <strong>Kids' Privacy</strong>
            </span>
          </strong>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            ‘
            <span style={{ fontFamily: "SimSun" }}>
              We collect information from kids under the age of 13 just to
              better our services. If You are a parent or guardian and You are
              aware
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            that Your child has provided Us with Personal Data without your
            permission, please contact Us. If We become aware that We have
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            collected Personal Data from anyone under the age of 13 without
            verification of parental consent, We take steps to remove that.
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            information from our servers.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            If we decide to change our privacy policy, we will post those
            changes on this page, and/or update the Privacy Policy modification
            date
          </span>
          &nbsp;<span style={{ fontFamily: "SimSun" }}>below.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We may display, include or make available third-party content
            (including data, information, applications and other products
            services)
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            or provide links to third-party websites or services ("Third- Party
            Services").
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            You acknowledge and agree that we shall not be responsible for any
            Third-Party Services, including their accuracy, completeness,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            timeliness, validity, copyright compliance, legality, decency,
            quality or any other aspect thereof. We do not assume and shall not
            have
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            any liability or responsibility to you or any other person or entity
            for any Third-Party Services.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Third-Party Services and links thereto are provided solely as a
            convenience to you and you access and use them entirely at your own
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            risk and subject to such third parties
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              ’&nbsp;
            </span>
            <span style={{ fontFamily: "SimSun" }}>terms and conditions.</span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Facebook pixel is an analytics tool that allows you to measure the
            effectiveness of your advertising by understanding the actions
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            people take on your website. You can use the pixel to: Make sure
            your ads are shown to the right people. Facebook pixel may collect
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            information from your device when you use the service. Facebook
            pixel collects information that is held in accordance with its
            Privacy
          </span>
          &nbsp;<span style={{ fontFamily: "SimSun" }}>Policy.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <strong>
            <span style={{ fontFamily: "SimSun" }}>
              <strong>* Google Maps APIs</strong>
            </span>
          </strong>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Google Maps API is a robust tool that can be used to create a custom
            map, a searchable map, check-in functions, display live data
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            synching with location, plan routes, or create a mashup just to name
            a few.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Google Maps API may collect information from You and from Your
            Device for security purposes.
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            Google Maps API collects information that is held in accordance with
            its Privacy Policy.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <strong>
            <span style={{ fontFamily: "SimSun" }}>
              <strong>* Cookies</strong>
            </span>
          </strong>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We use Cookies to enhance the performance and functionality of our
            service but are non-essential to their use. However, without
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            these cookies, certain functionality like videos may become
            unavailable or you would be required to enter your login details
            every
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            time you visit our service as we would not be able to remember that
            you had logged in previously.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <strong>
            <span style={{ fontFamily: "SimSun" }}>
              <strong>* Local Storage</strong>
            </span>
          </strong>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Local Storage sometimes known as DOM storage, provides web apps with
            methods and protocols for storing client-side data. Web
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            storage supports persistent data storage, similar to cookies but
            with a greatly enhanced capacity and no information stored in the
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>HTTP request header.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <strong>
            <span style={{ fontFamily: "SimSun" }}>
              <strong>+ Sessions</strong>
            </span>
          </strong>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We use "Sessions" to identify the areas of our website that you have
            visited. A Session is a small piece of data stored on your
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            computer or mobile device by your web browser.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We may be collecting and using information from you if you are from
            the European Economic Area (EEA), and in this section of our
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            Privacy Policy we are going to explain exactly how and why is this
            data collected, and how we maintain this data under protection
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            from being replicated or used in the wrong way.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            GDPR is an EU-wide privacy and data protection law that regulates
            how EU residents
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              ’&nbsp;
            </span>
            <span style={{ fontFamily: "SimSun" }}>
              data is protected by companies and enhances
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            the control the EU residents have, over their personal data.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Any data that relates to an identifiable or identified individual.
            GDPR covers a broad spectrum of information that could be used on
            its
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            own, or in combination with other pieces of information, to identify
            a person. Personal data extends beyond a person's name or email
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            address. Some examples include financial information, political
            opinions, genetic data, biometric data, IP addresses, physical
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            address, sexual orientation, and ethnicity. The Data Protection
            Principles include requirements such as:
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Personal data collected must be processed in a fair, legal, and
              transparent way and should only be used in a way that a person
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>would reasonably expect.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Personal data should only be collected to fulfil a specific
              purpose and it should only be used for that purpose. Organizations
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            must specify why they need the personal data when they collect it.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Personal data should be held no longer than necessary to fulfil
              its purpose.
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              People covered by the GDPR have the right to access their own
              personal data. They can also request a copy of their data, and
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            that their data be updated, deleted, restricted, or moved to another
            organization.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            GDPR adds some new requirements regarding how companies should
            protect individuals
            <span style={{ fontFamily: "Courier New,Courier,monospace" }}>
              ’&nbsp;
            </span>
            <span style={{ fontFamily: "SimSun" }}>
              personal data that they collect and
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            process. It also raises the stakes for compliance by increasing
            enforcement and imposing greater fines for breach. Beyond these
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            facts it's simply the right thing to do. At Help Scout we strongly
            believe that your data privacy is very important and we already have
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            solid security and privacy practices in place that go beyond the
            requirements of this new regulation.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <strong>
            <span style={{ fontFamily: "SimSun" }}>
              <strong>Individual Data Subject's Rights - Data Access,</strong>
            </span>
          </strong>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We are committed to helping our customers meet the data subject
            rights requirements of GDPR. We process or store all personal
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            data in fully vetted, DPA compliant vendors. We do store all
            conversation and personal data for up to 6 years unless your account
            is
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            deleted. In which case, we dispose of all data in accordance with
            our Terms of Service and Privacy Policy, but we will not hold it
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>longer than 60 days.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We are aware that if you are working with EU customers, you need to
            be able to provide them with the ability to access, update,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            retrieve and remove personal data. We got you! We've been set up as
            self service from the start and have always given you access
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            to your data and your customers data. Our customer support team is
            here for you to answer any questions you might have about
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>working with the API.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            The California Consumer Privacy Act (CCPA) requires us to disclose
            categories of Personal Information we collect and how we use it,
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            the categories of sources from whom we collect Personal Information,
            and the third parties with whom we share it, which we have
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>explained above.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We are also required to communicate information about rights
            California residents have under California law. You may exercise the
          </span>
          &nbsp;<span style={{ fontFamily: "SimSun" }}>following rights:</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Right to Know and Access. You may submit a verifiable request for
              information regarding the: (1) categories of Personal
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            Information we collect, use, or share; (2) purposes for which
            categories of Personal Information are collected or used by us; (3)
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            categories of sources from which we collect Personal Information;
            and (4) specific pieces of Personal Information we have
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>collected about you.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Right to Equal Service. We will not discriminate against you if
              you exercise your privacy rights.
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Right to Delete. You may submit a verifiable request to close your
              account and we will delete Personal Information about you
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>that we have collected.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Request that a business that sells a consumer's personal data, not
              sell the consumer's personal data.
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            If you make a request, we have one month to respond to you. If you
            would like to exercise any of these rights, please contact us.
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            We do not sell the Personal Information of our users.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            For more information about these rights, please contact us.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            CalOPPA requires us to disclose categories of Personal Information
            we collect and how we use it, the categories of sources from
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            whom we collect Personal Information, and the third parties with
            whom we share it, which we have explained above.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <strong>
            <span style={{ fontFamily: "SimSun" }}>
              <strong>CalOPPA users have the following rights:</strong>
            </span>
          </strong>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Right to Know and Access. You may submit a verifiable request for
              information regarding the: (1) categories of Personal
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            Information we collect, use, or share; (2) purposes for which
            categories of Personal Information are collected or used by us; (3)
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>
            categories of sources from which we collect Personal Information;
            and (4) specific pieces of Personal Information we have
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>collected about you.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Right to Equal Service. We will not discriminate against you if
              you exercise your privacy rights.
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Right to Delete. You may submit a verifiable request to close your
              account and we will delete Personal Information about you
            </span>
          </span>
          &nbsp;
          <span style={{ fontFamily: "SimSun" }}>that we have collected.</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            «&nbsp;
            <span style={{ fontFamily: "SimSun" }}>
              Right to request that a business that sells a consumer's personal
              data, not sell the consumer's personal data.
            </span>
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            If you make a request, we have one month to respond to you. If you
            would like to exercise any of these rights, please contact us.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            We do not sell the Personal Information of our users.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            For more information about these rights, please contact us.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            Don't hesitate to contact us if you have any questions.
          </span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>&nbsp;</p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>+ Via Email:&nbsp;</span>
          <span style={{ fontFamily: "SimSun" }}>info</span>
          <span style={{ fontFamily: "SimSun" }}>@pakatron.com</span>
        </span>
      </span>
    </span>
  </p>
  <p style={{ textAlign: "start" }}>
    <span style={{ fontSize: "medium" }}>
      <span style={{ fontFamily: "SimSun" }}>
        <span style={{ color: "#000000" }}>
          <span style={{ fontFamily: "SimSun" }}>
            + Via Phone Number: +1 516 461 9526
          </span>
        </span>
      </span>
    </span>
  </p>
  </div>
</>



    )
}

export default privacy