import React from 'react'
import Heading from './components/Heading'
import { NextSeo } from 'next-seo'

const terms = () => {
  return (
    <>
          <NextSeo
        title="Excel Travel Services"
        description="Welcome to Excel travel Services. We are your AfricanTour Experts. Book yourflights, Hotels, Cars with us. We are the best in the world." />
    <Heading title={'Terms & Conditions'} subtitle={`These Terms and Conditions govern the use of all services offered and operated. Kindly appraise yourself with the information presented below `} imageSrc={'/images/cards/holiday5.jpg'}  />
    <div className="container mx-auto px-10 py-10 my-5 font-sans  text-slate-900 dark:text-white dark:bg-slate-800 bg-gray-100 rounded-xl ">

    <div className="font-bold text-xl ">Carefully Read The Following</div> <br />

    <p>YOU MUST REVIEW YOUR TRAVEL ITINERARY CAREFULLY TO MAKE SURE THERE ARE NO MISTAKES (DATES, NAMES, ETC.). FAILURE TO DO SO MAY RESULT IN YOUR INABILITY TO USE THE AIRLINE TICKET AND CANCELLATION OF THE RESERVATION.
    
         </p> <br />
    <p>
    
    DUE TO RISING FUEL COSTS, AIRLINES ARE CANCELING MANY FLIGHTS. IF THERE IS A SCHEDULE CHANGE THAT REQUIRES TICKETS TO BE EXCHANGED DUE TO THE AIRLINES ACTIONS, THERE WILL BE A FEE OF $25.00 IMPOSED PER RESERVATION.
    
    IF YOUR CREDIT CARD DECLINES THE CHARGE FOR THE TICKET THERE WILL BE A $25.00 ADMINISTRATIVE FEE APPLIED PER PERSON.
    
         </p> <br />
    <p>
    
    NEW BAGGAGE RESTRICTIONS APPLY FOR DOMESTIC TRAVEL. PLEASE CALL YOUR AIRLINE FOR SPECIFIC DETAILS. AFTER A CONFIRMATION NUMBER IS ISSUED, A RESERVATION CAN BE VOIDED NO LATER THAN 24 HOURS AFTER IT HAS BEEN ISSUED. THE VOID PENALTY OF $100.00 PER TICKET WILL APPLY.
    
    ALL CANCELLATIONS (WHERE PERMITTED) ARE SUBJECT TO AN AIRLINE PENALTY, PLUS $100.00 PER PERSON SERVICE FEE. WHEN A REFUND IS REQUESTED, THE PROCESS CAN TAKE UP TO 6-8 WEEKS. DEBIT CARD REFUNDS MAY TAKE LONGER.
    
    ALL CHANGES (WHERE PERMITTED) ARE SUBJECT TO AN AIRLINE PENALTY, PLUS $100.00 PER PERSON SERVICE FEE. IF THE NEW TICKET IS A HIGHER COST, THE DIFFERENCE IN THE NEW FARE MUST ALSO BE COLLECTED.
        </p> <br />
    <p>    </p> <br />
    <p>
     
    
    ALL CANCELLATIONS OR CHANGES MUST BE PROCESSED PRIOR TO YOUR SCHEDULED DEPARTURE DATE.
    
         </p> <br />
    <p>    </p> <br />
    <p>
    
    SEAT ASSIGNMENTS AND SPECIAL MEAL REQUESTS WILL BE CONVEYED TO THE AIRLINES, BUT CANNOT BE GUARANTEED. SEATS FOR ALL PASSENGERS TRAVELING TOGETHER WILL BE SELECTED AUTOMATICALLY AND ADJACENT TO THE PRIMARY PASSENGER, BASED ON BEST SEATS AVAILABLE AT THE TIME OF REQUEST.
    
        </p> <br />
    <p>    </p> <br />
    <p> 
    
    SOME AIRLINES WILL ALLOW SPECIAL WAIVERS IN THE CASE OF MEDICAL EMERGENCY FOR CANCELING A TRIP. THEY REQUIRE ALL HOSPITAL AND DOCTOR DOCUMENTATION TO CONSIDER ON A CASE BY CASE BASIS. IF YOU HAVE A MEDICAL EMERGENCY AND NEED TO CANCEL, PLEASE NOTE THAT THERE IS A $50 PER PERSON CHARGE TO INITIATE THIS REFUND. SEND AN EMAIL TO AGENT@THOMALEX.COM FOR MORE INFORMATION OR CALL 877 700 3535.
    
         </p> <br />
    <p>    </p> <br />
    <p>
    
    PLEASE ALLOW FOR SHIPPING TIME OF PAPER-TICKETS, AS WE MUST HAVE THEM IN OUR POSSESSION BEFORE SCHEDULED DEPARTURE TO MAKE ANY CANCELLATION OR CHANGES, OTHERWISE THE RESERVATION WILL BE CONSIDERED A «NO SHOW» AND YOU WILL NOT BE ELIGIBLE FOR A REFUND OR CHANGE. TICKETS ARE NOT VALID FOR RESALE OR TRANSFER. NAMES SHOWN ON TICKETS CANNOT BE CHANGED AND MUST MATCH THE PASSENGER’S PASSPORT.
    
         </p> <br />
    <p>    </p> <br />
    <p>
    
    SPECIAL OFFERS, COUPONS, OR CREDITS MAY NOT BE APPLIED TO THE ONLINE AIRFARES.
    
    ALL PAPER TICKETS SHIPPED TO NON-US ADDRESSES ARE SUBJECT TO INTERNATIONAL SHIPPING FEES.
    
        </p> <br />
    <p>    </p> <br />
    <p> 
    
    IN SOME CASES A TICKET THAT IS INDICATED AS ELECTRONIC AT THE TIME OF BOOKING WILL HAVE TO BE ISSUED AS A PAPER TICKET. THIS IS BEYOND OUR CONTROL AND DEPENDS ON AIRLINES ROUTING AND AGREEMENTS WITH OTHER CARRIERS. IN SUCH CASES WE WILL SHIP THE PAPER TICKETS USING FEDERAL EXPRESS, ADDITIONAL SHIPPING COSTS WILL APPLY.
    
        </p> <br />
    <p>    </p> <br />
    <p> 
    
    IF YOUR TICKETS CANNOT BE PROCESSED FOR ANY REASON, YOU WILL BE NOTIFIED VIA EMAIL WITHIN TWO (2) BUSINESS DAYS AND YOUR PAYMENT WILL NOT BE PROCESSED.
    
     
    
    IT IS YOUR RESPONSIBILITY TO RECONFIRM YOUR FLIGHTS DIRECTLY WITH THE AIRLINES AT LEAST 72 HOURS PRIOR TO YOUR DEPARTURE DATE (OUTBOUND AND INBOUND). WE ARE NOT RESPONSIBLE FOR AIRLINES SCHEDULE CHANGES. THE AIRLINE HAS THE RIGHT TO ADJUST/CHANGE AND CANCEL FLIGHTS UP TO THE DAY OF DEPARTURE.
    
     
    
    WE ARE NOT RESPONSIBLE FOR ANY MISCONNECTIONS THAT THE AIRLINES MIGHT CAUSE. WE ARE NOT LIABILITY FOR CANCELLED FLIGHTS, FLIGHTS THAT ARE MISSED OR FLIGHTS WITH MISCONNECTION DUE TO ANY AIRLINE SCHEDULED CHANGES. WE ARE NOT ABLE TO COMPENSATE FOR HOTEL OVERNIGHTS IF SUCH MAY OCCUR DUE TO AN AIRLINE SCHEDULE CHANGE. IT IS YOUR RESPONSIBILITY TO COORDINATE WITH THE AIRLINE DIRECTLY ANY CHANGES THAT MIGHT AFFECT YOUR TRAVEL.
    
     
    
    IF THE AIRLINE IS PROVIDING A FULL REFUND DUE TO MAJOR SCHEDULE CHANGE; YOU WILL BE RESPONSIBLE FOR THE PURCHASE OF THE NEW TICKET WITH ANOTHER CARRIER. MONEY TRANSFER FROM AIRLINE TO ANOTHER IS NOT ALLOWED. AIRLINE REFUNDS TAKE BETWEEN 6-8 WEEKS.
    
     
    
    CHILDREN’S FARES APPLY TO PASSENGERS BETWEEN THE AGE OF 2 AND 11 YEARS OLD.
    IF A MINOR (16 YEARS OR YOUNGER) TRAVELS ALONE, IT IS THE PASSENGERS RESPONSIBILITY TO CHECK WITH THE AIRLINE DIRECTLY IN REGARDS TO FEES AND ACCEPTANCE OF MINORS.
    INFANT FARES ARE FOR PASSENGERS UNDER THE AGE OF 2.
    
    ADULT FARES ARE FOR PASSENGERS 12 AND OLDER.
    
     
    
    PURCHASE OF OPTIONAL TRAVEL INSURANCE IS STRONGLY RECOMMENDED. WE CANNOT WAIVE PENALTIES IMPOSED BY THE AIRLINES. INSURANCE PRODUCTS ARE 100% NON REFUNDABLE ONCE PURCHASED.
    
    ALTHOUGH MOST TRAVEL, INCLUDING TRAVEL TO INTERNATIONAL DESTINATIONS, IS COMPLETED WITHOUT INCIDENT, TRAVEL TO CERTAIN DESTINATIONS MAY INVOLVE GREATER RISK THAN OTHERS. PASSENGERS ARE ADVISED TO REVIEW TRAVEL PROHIBITIONS, WARNINGS, ANNOUNCEMENTS AND ADVISORIES ISSUED BY THE UNITED STATES GOVERNMENT PRIOR TO BOOKING TRAVEL TO INTERNATIONAL DESTINATIONS. INFORMATION ON CONDITIONS IN VARIOUS COUNTRIES AND THE LEVEL OF RISK ASSOCIATED WITH TRAVEL TO PARTICULAR INTERNATIONAL DESTINATIONS CAN BE FOUND AT WWW.STATE.GOV, WWW.TSA.GOV, WWW.DOT.GOV, WWW.FAA.GOV, WWW.CDC.GOV, WWW.TREAS.GOV/OFAC AND WWW.CUSTOMS.GOV .
    
    </p> <br />
    <p>
    
    FOR INTERNATIONAL TRAVEL, IT IS ALWAYS IMPORTANT TO CHECK THE «ENTRY REQUIREMENTS» FOR THE COUNTRIES THAT YOU WILL BE VISITING. IT IS ALSO VERY IMPORTANT TO CHECK TO SEE IF ANY VISAS MAY BE REQUIRED. VISAS AND PASSPORTS MUST BE CURRENT AND UP TO DATE. SOME COUNTRIES WILL NOT ALLOW ENTRY WITH A ONE WAY TICKET.
    
    CHECK ALL RULES AND REGULATIONS BEFORE PURCHASING A TICKET. AIRLINES DO NOT REFUND OR WAIVE PENALTIES DUE TO IMPROPER DOCUMENTATION. THIS IS THE SOLE RESPONSIBILITY OF EACH PASSENGER.
    
    </p> <br />
    <p>
    
    CHECK-IN AT THE AIRLINE COUNTER IS REQUIRED AT LEAST 3-4 HOURS PRIOR TO DEPARTURE FOR INTERNATIONAL TRAVEL AND 2 HOURS FOR DOMESTIC TRAVEL. LATE CHECK-IN MAY RESULT IN CANCELLATION OF THE RESERVATION. PETS ARE ALLOWED ON FLIGHTS BOOKED THROUGH OUR WEBSITE, PURSUANT TO THE AIRLINES INDIVIDUAL RESTRICTIONS AND REGULATIONS. PLEASE CHECK DIRECTLY WITH THE AIRLINE BEFORE BOOKING YOUR TRIP.
    </p> <br />
    <p>
     
    
    PETS ARE ALLOWED ON FLIGHTS BOOKED THROUGH OUR WEBSITE, PURSUANT TO THE AIRLINES INDIVIDUAL RESTRICTIONS AND REGULATIONS. PLEASE CHECK DIRECTLY WITH THE AIRLINE FOR INDIVIDUAL INFORMATION.
    
    </p> <br />
    <p>
    
    PLEASE NOTE THAT YOU MAY SEE SEVERAL CHARGES ON YOUR CREDIT CARD STATEMENT. THESE CHARGES MAY INCLUDE, AIRLINE TICKETS, AGENCY FEE, AND SHIPPING FEE THAT MAY APPLY. THIS WILL TOTAL THE AMOUNT THAT YOU AUTHORIZED. YOU MAY SEE A HOLD OF $1 ON YOUR BANK STATEMENT. THE CREDIT CARD VERIFICATION REQUIRES AUTHORIZING AT LEAST THIS AMOUNT TO PROCESS YOUR ORDER. THIS IS NOT A FEE AND YOU WILL NOT BE CHARGED THIS AMOUNT.
    
    </p> <br />
    <p>
    
    IF YOU ARE USING A DEBIT OR CHECK CARD, PLEASE CALL YOUR BANK AS SOON AS YOUR RESERVATION IS CONFIRMED, AND MAKE SURE TO RAISE THE DAILY ALLOWED SPENDING LIMIT TO COVER THE TOTAL PURCHASE AMOUNT, IF APPLICABLE. BY CONFIRMING THE RESERVATION, THE CUSTOMER ASSUMES THE BURDEN OF PROOF. IF THE CUSTOMER WISHES TO DISPUTE A CHARGE ON A CREDIT CARD FOR TRAVEL SERVICES PURCHASED, SHIPPING OR HANDLING CHARGES, TAXES, AND OTHER FEES OUTLINED TO THE CUSTOMER DURING THE BOOKING PROCESS, THE CUSTOMER AGREES THE BANK SHOULD NOT MAKE SUCH A CHARGE BACK AGAINST OUR COMPANY, OUR TICKET PROCESSOR, OR THE AIRLINE, UNTIL WE DISCUSS THE CHARGES WITH THE BANK AND THE BURDEN OF PROOF IS MET. WE ALSO RESERVE THE RIGHTS TO REPORT FRAUDULENT CREDIT CARD ACTIVITY AND INVALID DISPUTES TO THE APPROPRIATE AUTHORITIES AND CREDIT BUREAUS.
    
    </p> <br />
    <p className="font-bold">

    ALL FRAUDULENT CREDIT CARD TRANSACTIONS ARE TRACKED ELECTRONICALLY THROUGH MULTIPLE CHANNELS AND ARE REPORTED TO AIRLINE SECURITY, AIRPORT POLICE AND ALL LAW ENFORCEMENT AGENCIES.
    </p> <br />
    </div>
    </>
  )
}

export default terms